#!/bin/bash
chmod +x 进入工具
chmod +x datzj
chmod +x 主
chmod +x jzs
chmod +x MH
chmod +x wstuexp
chmod +x syy
chmod +x zjuexp
chmod +x 修改伪实体
chmod +x 抓载具
chmod +x zxb
chmod +x 淘汰播报
chmod +x wstzxb
chmod +x 音乐播放
chmod +x tqpz
chmod +x datjb
chmod +x zdat
chmod +x 自动写配料表
chmod +x uexpwxcjb
chmod +x uexpFL
chmod +x uexpdb
chmod +x datdb
chmod +x 64Kjb
chmod +x mroot
chmod +x dj
chmod +x sy/dbjb/fz
chmod +x sy/dbjb/paks
chmod +x sy/dbjb/quickbms
chmod +x sy/dbjb/unpack.bms
chmod +x sy/dbjb/打包.bms
chmod +x sy/dbjb/解包.bms
chmod +x sy/dbjb/非

base_dir="/storage/emulated/0/ST制作区"
sub_dirs=(
    "pak"
    "打包dat"
    "解包dat"
    "打包uexp"
    "解包uexp"
    "小包/伪实体"
    "小包/载具"
    "小包/非块存放"
    "提取配置/原pak"
    "提取配置/改pak"
    "提取dat储存区"
    "自动美化存放区"
)

# 创建主目录
mkdir -p "$base_dir" || {
    echo "无法创建目录，请检查存储权限！"
    exit 1
}

# 创建子目录
for dir in "${sub_dirs[@]}"; do
    mkdir -p "$base_dir/$dir" && echo "已创建: $base_dir/$dir"
done

echo "所有目录创建完成！"

./进入工具





